### ISSUE TITLE
phred quality values > 41?!

### ISSUE THREAD

**Issue by arperrotta** [bow/abifpy#5]
Hello,
I am using abifpy to generate fastq files from sanger ABIFs and the tool is quick and easy! But the range of quality values generated often exceed the Phred+33 cap of 41 which is breaking many of the tools I want to use downstream. 

Is there an option to specify Phred+33 so I can ensure that is indeed the encoding of the quality values? Or a way to cap the values at the more accepted 41? 

Thank you so much for your help

**Comment by bow** [comment]
Hi @arperrotta,

Thank you for the report. To be honest (and as mentioned in the [latest README](https://github.com/bow/abifpy/blob/master/README.rst)), I have not really maintained this specific module for some time now, since this was merged a long time ago with the [Biopython](https://github.com/biopython/biopython) project.

The functionalities of this module now live in Biopython in the `Bio.SeqIO` module. Since the merge, some updates have also been implemented (which may have addressed your issue).

I did not recall any specific change to the quality score handling though, so if you have a specific file where this issue occurs, I don't mind checking it for you (via email). But in the mean time, would you mind checking whether you can reproduce the issue with the latest Biopython? Feel free to reopen this issue in their issue tracker if the issue persists.

**Comment by arperrotta** [comment]
Thanks @bow! I was able to solve this issue using one of the parameters in a downstream tool (usearch) by adjusting the max quality value accepted. If I have any issues in the future though I will check Bio.SeqI0 first. 
thank you for your reply.
